name: Add Render link to jira issue

on:
  issue_comment:
    types: [created]
  pull_request_review:
  pull_request:
    types:
      [
        opened,
        closed,
        ready_for_review,
        review_requested,
        review_request_removed,
      ]
jobs:
  add-render-link-to-issue:
    runs-on: ubuntu-latest
    name: Add render link to issue
    if: github.event.issue.pull_request && contains(github.event.comment.user.login, 'render[bot]')
    steps:
      # https://github.com/marketplace/actions/jira-login
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      # https://github.com/ejnkr/get-jira-keys-from-pr
      - name: Get Jira keys
        id: getJiraKeys
        uses: ejnkr/get-jira-keys-from-pr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/marketplace/actions/github-script
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: format
        with:
          script: |
            const path = require('path');

            return require(path.resolve('.github/scripts/formatRenderComment.js'))({
              context
            });
          result-encoding: string
      # https://github.com/marketplace/actions/jira-add-comment
      - name: Comment on issue
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.getJiraKeys.outputs.jiraKeys }}
          comment: ${{ steps.format.outputs.result }}
