name: Jira Automations

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
# on:
#   issue_comment:
#     types: [created]
#   pull_request_review:
#   pull_request:
#     types:
#       [
#         opened,
#         edited,
#         reopened,
#         # closed,
#         # ready_for_review,
#         # review_requested,
#         # review_request_removed,
#       ]
#    discussion_comment:
#     types: [created]
#   # issue_comment:                                     
#   #   types: [created, edited, deleted]
# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#         run: echo "$GITHUB_CONTEXT"
#   print:
#     if: contains(github.event.comment.body, 'ender') 
#     runs-on: ubuntu-latest
#     steps:
#       # - name: Get repository code
#       #   uses: actions/checkout@v3
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#       - name: Print to console
#         env:
#           COMMENT: ${{ toJSON(github.event.comment) }}
#         run: |
#          echo "$COMMENT"
         
#   # add-render-link-to-issue:
#   #   name: Add render link to issue
#   #   if: github.event.issue.pull_request != '' && contains(github.event.comment.user.login, 'render[bot]')
#   #   runs-on: ubuntu-latest
#   #   env:
#   #     JIRA_AUTOMATION_USER: ${{secrets.JIRA_AUTOMATION_USER}}
#   #     JIRA_AUTOMATION_TOKEN: ${{secrets.JIRA_AUTOMATION_TOKEN}}
#   #   steps:
#   #     - uses: actions/checkout@v3
#   #     # - uses: actions/github-script@v4
#   #       with:
#   #         github-token: ${{secrets.GITHUB_TOKEN}}
#   #         script: |
#   #           const path = require('path');

#   #           return require(path.resolve('.github/scripts/jira-automations/actionComment.js'))({
#   #             github,
#   #             context,
#   #             actionName: 'renderLinkComment',
#   #           });