# name: Jira Automations

# on:
#   pull_request:
#     types: [opened]
#   issue_comment:
#     types: [created]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: khan/pull-request-comment-trigger@v1.1.0
#         id: check
#         with:
#           trigger: '@deploy'
#           reaction: rocket
#         env:
#           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
#       - run: 'echo Found it!'
#         if: steps.check.outputs.triggered == 'true'
on:
  issue_comment:
    types: [created]
  pull_request_review:
  pull_request:
    types:
      [
        opened,
        edited,
        reopened,
      ]
   discussion_comment:
    types: [created]
jobs:
  add-render-link-to-issue:
    name: Add render link to issue
    if: github.event.issue.pull_request != '' && contains(github.event.comment.user.login, 'render[bot]')
    runs-on: ubuntu-latest
    env:
      JIRA_AUTOMATION_USER: ${{secrets.JIRA_AUTOMATION_USER}}
      JIRA_AUTOMATION_TOKEN: ${{secrets.JIRA_AUTOMATION_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = require('path');

            return require(path.resolve('.github/scripts/jira-automations/actionComment.js'))({
              github,
              context,
              actionName: 'renderLinkComment',
            });