name: Jira Automations

on:
  issue_comment:
    types: [created]
  pull_request_review:
  pull_request:
    types:
      [
        # opened,
        closed,
        # ready_for_review,
        # review_requested,
        # review_request_removed,
      ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
      - name: Issue number
        run: echo '${{steps.get_issue_number.outputs.result}}'
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: render[bot]
          body-includes: Follow its progress at
      - name: Find in commit messages
        uses: atlassian/gajira-find-issue-key@v3
        id: get_issue_number
        with:
          from: branch
      - name: Comment on issue
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{steps.get_issue_number.outputs.result}}
          comment: ${{steps.get_issue_number.outputs.result}} ${{ steps.fc.outputs.comment-body }}