# This is a basic workflow to help you get started with Actions

name: Quality Checks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches:
      - '**'

jobs:
  apply-team-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = require('path');

            return require(path.resolve('.github/scripts/apply-team-label.js'))({
              github,
              context,
              ref: '${{github.head_ref}}',
            });
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: |
          echo "@yaradigitallabs:registry=https://npm.pkg.github.com/" > ${{ github.workspace }}/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ${{ github.workspace }}/.npmrc
      - run: yarn
      - name: Commitlint CLI
        uses: wagoid/commitlint-github-action@v2
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
        with:
          configFile: commitlint.config.js
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4.9.6
        env:
          ACTIONS_RUNNER_DEBUG: false
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: true
          VALIDATE_CSS: true
          VALIDATE_JSON: true
          VALIDATE_JSX: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          LINTER_RULES_PATH: ''
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prettier check
        uses: creyD/prettier_action@v3.0
        with:
          dry: true
