name: Semantic Pull Request Title
on:
  pull_request_target:
    branches-ignore:
      - stable
    types:
      - opened
      - edited
      - synchronize
jobs:
  validate-pull-request-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # When using "Squash and merge" on a PR with only one commit, GitHub will suggest using that commit message instead of the PR title for the merge commit, and it's easy to commit this by mistake. Enable this option to also validate the commit message for one commit PRs.
          validateSingleCommit: true
