# name: Sync Codegen - Self Host Runner
# # This workflow is triggered on pushes to the repository.
# on:
#   workflow_dispatch:
#   # TODO: This is a workaround till we have apollo studio schema change hook available
#   schedule:
#     - cron: '*/10 * * * *'

# env:
#   NO_COLOR: true
#   CI: 1
#   # FULL_TOKEN is required because we merge PRs with branch protection
#   # If we enable branch protection rules for administrators in the future, this will break
#   GITHUB_TOKEN: ${{ secrets.FULL_TOKEN }}
#   GRAPHQL_URL: ${{ secrets.INTEGRATION_URL }}

# jobs:
#   build_run:
#     runs-on: gh-runner-emea-stage
#     name: Update GraphQL Schema SELF Hosted Instance
#     if: github.ref == 'refs/heads/main' # Run only on "main" branch
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16'

#       - name: Install Yarn
#         run: npm install -g yarn

#       - name: Turnstyle
#         uses: softprops/turnstyle@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Add .npmrc file
#         run: |
#           echo "@yaradigitallabs:registry=https://npm.pkg.github.com/" > ${{ github.workspace }}/.npmrc
#           echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ${{ github.workspace }}/.npmrc

#       - uses: bahmutov/npm-install@v1
#         with:
#           install-command: yarn --frozen-lockfile

#       - name: Run Codegen
#         run: yarn types:generate

#       - name: Have Types Changed
#         id: have-types-changed
#         run: node scripts/sync-codegen/gitFilesStatus.js src/graphql/types.ts src/graphql/introspection.json

#       - name: Set Head Branch Name
#         id: head-branch-name
#         if: ${{ steps.have-types-changed.outputs.HAS_CHANGED == 'true' }}
#         run: |
#           HEAD_BRANCH=$(node scripts/sync-codegen/headBranchName.js)
#           echo $HEAD_BRANCH
#           echo '::set-output name=HEAD_BRANCH::'$HEAD_BRANCH

#       - name: Push To Branch
#         if: ${{ steps.have-types-changed.outputs.HAS_CHANGED == 'true' }}
#         uses: github-actions-x/commit@v2.9
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           push-branch: ${{ steps.head-branch-name.outputs.HEAD_BRANCH }}
#           commit-message: 'chore(graphql): update automatically generated types [skip ci]'
#           force-add: 'true'
#           files: src/graphql/types.ts src/graphql/introspection.json
#           name: Botato
#           email: CR000038@yara.com
#           rebase: 'false' # We can't make this true because "push-branch" is always a new branch

#       - name: Create PR
#         id: create-pr
#         if: ${{ steps.have-types-changed.outputs.HAS_CHANGED == 'true' }}
#         run: node scripts/sync-codegen/createPR.js --head-branch ${{ steps.head-branch-name.outputs.HEAD_BRANCH }}

#       - name: Merge PR
#         if: ${{ steps.have-types-changed.outputs.HAS_CHANGED == 'true' }}
#         run: node scripts/sync-codegen/mergePR.js --head-branch ${{ steps.head-branch-name.outputs.HEAD_BRANCH }} --pr-number ${{ steps.create-pr.outputs.PR_NUMBER }}
